### ISSUE TITLE
Odom Topic

### ISSUE THREAD

**Issue by Morgantiz** [ADVRHumanoids/concert_description#10]
To develop the navigation stack it would be useful to have an "/odom" topic of type nav_msgs/Odometry (http://docs.ros.org/en/noetic/api/nav_msgs/html/msg/Odometry.html) where it is published the velocity of robot with respect to the robot base_link. 

I also noticed that in the topic /concert_odometry/base_link/twist the covariances are zero (do they have the right value?).
Instead, what covariances do the values in the topic /concert_odometry/base_link/pose have?.

In particular we need a message of type nav_msgs/Odometry coming from the robot. This must have the child_frame_id equal to the "base_link" of the robot and the frame_id inside the header must be "odom." It must also contain at least the robot's velocities with respect to the base_link (e.g., positive x velocities if it is moving forward) and non-zero covariances ( e.g. could be just the values along the diagonal equal to 0.05). 
This message is needed to then filter with an EKF and estimate the tf between "odom" and "base_link". Then this estimate will be corrected with localization by sensors.

**Comment by EdoardoRomiti** [comment]
Hi @Morgantiz this was implemented and in the last commit e5e97673ebfc827f5ec0974fdd5d9db5fe0c6871 there is also the possibility to set the covariance from config file ([concert_odometry.yaml](https://github.com/ADVRHumanoids/concert_description/blob/master/concert_odometry/config/concert_odometry.yaml)). If you work with source remember to pull also the [ADVRHumanoids/base_estimation](https://github.com/ADVRHumanoids/base_estimation) repo.
If you work with docker instead just pull the new docker. 
The name of the topic is **/concert_odometry/base_link/odom**.
Can you give it a try?

**Comment by Morgantiz** [comment]
I am testing it, thank you. It seems to be starting to work!
