### ISSUE TITLE
Manipulator part of URDF doesn't have joint limits

### ISSUE THREAD

**Issue by JakobThumm** [ADVRHumanoids/concert_description#19]
The created URDF doesn't have joint limits as far as I can see.
Where can I find these values for our safety shield?

**Comment by EdoardoRomiti** [comment]
What do you mean?
The joint limits can be found in the generated urdf, for instance:
```
<joint name="J1_E" type="revolute">
    <axis rpy="0 0 0" xyz="0 0 1"/>
    <parent link="J1_E_stator"/>
    <child link="L_1_E"/>
    <origin rpy="0.0 -0.0 0.0" xyz="0.0 0.0 0.22316"/>
    <limit effort="460.0" lower="-3.0" upper="3.0" velocity="2.14"/>
</joint>
```
If you are just interested in the joint limits you can look at the [json files](https://github.com/ADVRHumanoids/concert_resources/tree/5ee561489db865543808ea4c7c94f87cbe7519ea/json/concert) stored in concert_resources. We use the same format you guys use at TUM so you should be familiar with it.

**Comment by JakobThumm** [comment]
Ah, I was looking at the wrong entries.
I'm sorry for that!
Thanks for the quick answer.
