### ISSUE TITLE
Could not run IK control in RViZ

### ISSUE THREAD

**Issue by JakobThumm** [ADVRHumanoids/concert_description#4]
Hi,
I am trying to run the last step from the README: https://github.com/ADVRHumanoids/concert_description#move-the-base-with-ik
Unfortunately, I run into this error:
```
    /ros_server_node: [ok  ] OpenSotBackEndQPOases so library found! 
    /ros_server_node: [err ] ERROR: INITIALIZING STACK 1 
    /ros_server_node: terminate called after throwing an instance of 'std::runtime_error'
    /ros_server_node:   what():  Can Not initizalize SoT!
               /rviz: [RenderWindow* rviz::RenderSystem::makeRenderWindow]: Stereo is NOT SUPPORTED
               /rviz: [RenderSystem::detectGlVersion]: OpenGL device: Quadro RTX 4000/PCIe/SSE2
               /rviz: [RenderSystem::detectGlVersion]: OpenGl version: 4.6 (GLSL 4.6).
    /ros_server_node: /ros_server_node died from signal 6
    /ros_server_node: /ros_server_node left a core dump
    /ros_server_node: Determined pattern '/tmp/rosmon-node-x1tlg1/core'
    /ros_server_node: Could not find a matching core file :-(

```
Steps I took:
Run docker:
```
cd docker && ./run-docker.bash
```
Start roscore:
```
roscore
```
Start simulation:
```
mon launch concert_gazebo concert.launch rviz:=true
```
Start xbot2 GUI:
```
xbot2-gui
```
Enabled roscontrol in GUI.
Launched concert cartesio:
```
mon launch concert_cartesio concert.launch xbot:=true gui:=true
```
--> This threw the above error.
RViZ looks like this:
![image](https://user-images.githubusercontent.com/44090142/212674442-6c26c589-f1b4-4f3c-a43f-20d4aa8a23a3.png)
Gazebo looks fine as I can judge.

**Comment by EdoardoRomiti** [comment]
Hi @JakobThumm , this should be solved easily if you run the **homing plugin** before running the IK example.
The 0 value of the joints results in a singular configuration of the arm, which is a bad configuration to start the IK in and triggers this issue. After running the homing this should not happen anymore.

So before running ```mon launch concert_cartesio concert.launch xbot:=true gui:=true``` just either:
- start the homing plugin through the xbot2 GUI
- or run ```rosservice call /xbotcore/homing/switch "data: true"``` to start it from the terminal

**Comment by alaurenzi** [comment]
I have updated the readme according to what @EdoardoRomiti suggests

**Comment by JakobThumm** [comment]
I tested homing first and it works. Thanks :)
