### ISSUE TITLE
Forest Grow Error

### ISSUE THREAD

**Issue by Morgantiz** [ADVRHumanoids/concert_description#6]
I pulled the new commits on the repository and i can no longer do the docker build using the script build-docker.bash inside the docker folder.

![Screenshot from 2023-01-20 10-43-20](https://user-images.githubusercontent.com/60438336/213664701-3a1696dc-9fc8-4ee0-a579-b870b0400f0e.png)

**Comment by EdoardoRomiti** [comment]
You'll need to also update the forest recipes. From `concert_ws/recipes/multidof_recipes` you'll need to fetch and pull.

**Comment by fmros** [comment]
Running `build-docker.sh --no-cache` resolves the issue. Referencing comment [here](https://github.com/ADVRHumanoids/concert_description/pull/7#issuecomment-1399246490). @Morgantiz Please try and close issue.
